name: Run UI Tests

on: [pull_request, workflow_dispatch]

jobs:

  container-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Build TypeScript commons
      working-directory: ./commons/ts
      run: npm install && npm run build
    - name: Install Booking UI dependencies
      working-directory: ./booking-ui
      run: npm install
    - name: Run Booking UI linting
      working-directory: ./booking-ui
      run: npm run lint
    - name: Install Admin UI dependencies
      working-directory: ./admin-ui
      run: npm install
    - name: Run Admin UI linting
      working-directory: ./admin-ui
      run: npm run lint